server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            #- Between=2024-03-17T21:00:00.218129200+08:00[Asia/Shanghai],2024-03-17T21:01:00.218129200+08:00[Asia/Shanghai]  #在这个时间之后才能够访问，到点放票
            #- Header=X-Request-Id, \d+  #只有X-Request-Id属性为正整数才能访问
            #- Query=username,\d+  #要有参数名称为username并且值还要是整数才能路由
            #- RemoteAddr=10.2.142.1/24  # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
            #- Method=GET,POST   #只能是get或post请求方法
            #- My=diamond  #自定义的断言
#            - name: My
#              args:
#                userType: diamond     #使用完全展开的方式配置
                
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
            #- Cookie=username, zm
            #- Host=**.zmblog.com,**.zm.cn  #请求host的header值带zmblog.com或zm.cn的可以匹配

        - id: pay_routh3
          uri: lb://cloud-payment-service
          predicates:
             - Path=/pay/gateway/filter/**
           # - Path=/gateway/filter/**    #实际上你应该在浏览器输入http://localhost:9527/gateway/filter
             #- Path=/ZM/abcd/{segment}  #修改访问路径，{segment}占位符的内容会和SetPath的{segment}保持一致

          filters:
             -  My=zm #自定义的过滤器
             #- RedirectTo=302,http://www.zmblog.vip #访问localhost:9527/pay/gateway/filter/ 直接跳转到我的个人博客上
             #- SetPath=/pay/gateway/{segment}
             #- PrefixPath=/pay   #和上面的Path拼在一起就是http://localhost:9527/pay/gateway/filter
            #- AddRequestHeader=X-Request-zm1,zmValue1  #请求头kv，如果一头含有多参数则重写一行设置指定请求头内容
            #- AddRequestHeader=X-Request-zm2,zmValue2  #请求头kv，如果一头含有多参数则重写一行设置
#            - RemoveRequestHeader= sec-fetch-site #删除请求头sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode,myNavigate  #把请求头名为sec-fetch-mode的请求值修改成myNavigate
#            - AddRequestParameter=customerID,9527 #新增请求参数的kv
#            - RemoveRequestParameter=customerName        # 删除url请求参数customerName，你传递过来也是null
#            - AddResponseHeader=X-Response-zm,ZMResponse #新增一个响应头X-Response-zm并设值为ZMResponse
#            - SetResponseHeader=Date,2066-12-25 #修改响应头时间Date为2066-12-25
#            - RemoveResponseHeader=Content-Type #将自带的Content-Type 响应属性删除

